version: '3.8'
services:
  todolistapi:
    build: ./services/todoListApi
    restart: always
    ports:
      - 9001:9001
    networks:
      - todolistapi-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?allowPublicKeyRetrieval=true
      - spring.datasource.username=$MYSQLDB_USER
      - spring.datasource.password=$MYSQLDB_PASSWORD
    depends_on:
      - mysqldb

  todolistwebapp:
    build: ./services/todoListWebapp
    restart: always
    ports:
      - 9000:9000
    networks:
      - todolistapi-net
    depends_on:
      - todolistapi

  mysqldb:
    image: "mysql:8.0"
    restart: always
    expose:
      - $MYSQLDB_DOCKER_PORT
    networks:
      - todolistapi-net
    environment:
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_PASSWORD
      MYSQL_ROOT_PASSWORD: MYSQLDB_ROOT_PASSWORD
networks:
  todolistapi-net:
